### PR TITLE
Add uk customisation document and lbs to kg

### PR DESCRIPTION
**Pull request by brittainmark**
Add lbs to kg and uk customisation files

Scott I think you asked for these some time ago. I have just got around to doing them.

Please check I have the formatting and linking correct.

### CODE REVIEW

**Comment by scottcwilson** [comment]
In the first file, would you please pull in the "lbs to kg" content from /user/template/basic_customizations.md and just point that section to your new file.  Thanks.

**Comment by brittainmark** [comment]
OK think I have done that. 
Is there a way of including a file, so the details can be in the basic configuration file to save having to click the link?
Could I use` {{include.html "/user/localization/changing_weight_to_kg.md"}}` instead of the link?

Or assuming we are still using Hugo. Add a new function
include-file.html
```
{{ $file := .Get 0 }}
{{- .Page.Site.GetPage $file | .Render}}
```
then the markdown
```
{{< include-file " /user/localization/changing_weight_to_kg.md" >}}
```

**Comment by scottcwilson** [comment]
There is but I only use it for small bits.  See 

https://github.com/zencart/documentation/blob/master/CONTRIBUTING.md#shared-content

**Comment by scottcwilson** [comment]
Thanks for this - good additions for our UK friends.

**Pull request merged**
