### PR TITLE
Change load point to 200

### PR DESCRIPTION
**Pull request by brittainmark**
The load point change to 200 prior to 1.5.7 so have updated to 200.

### CODE REVIEW

**Comment by scottcwilson** [comment]
You sure?  In 158, includes/auto_loaders/config.products_viewed_counter.php loads products_viewed_counter at 190. 

Perhaps only the first two in the paragraph should be changed to 200, and not the code example?

**Comment by brittainmark** [comment]
To quote includes/autoloaders/config.core.php
```
/**
 * NOTE: Most plugins should be added from point 200 onward.
 */
```

**Comment by scottcwilson** [comment]
Fair  - but then should we change the sample code to a contrived example vs a real one that's loaded at 190?

**Comment by brittainmark** [comment]
Should we change includes/auto_loaders/config.products_viewed_counter.php to 200 to fit in with the new thinking 200.
In fact, should we change all the 190 to 200. I have tested config.products_viewed_counter.php, and it works fine at 200?

I have just checked and that is the only module that uses [190] as a load point in the release 1.5.8

I think it would look odd to say use 200 and give an example of using [190]

Happy to PR 200 change if you want it done

**Comment by scottcwilson** [comment]
The 200 is good, but let's change the code examples so `products_viewed_counter` becomes `example` in both places.

**Comment by brittainmark** [comment]
Changes made.

**Comment by scottcwilson** [comment]
It still says "products_viewed_counter"

**Pull request merged**
