### PR TITLE
Image resizing 2

### PR DESCRIPTION
**Pull request by wiztechinc**
edit images/html #406

### CODE REVIEW

**Comment by scottcwilson** [comment]
Please add links to the preview showing your changes - see https://github.com/zencart/documentation/blob/master/CONTRIBUTING.md#pr-content

**Comment by wiztechinc** [comment]
Thanks, I was looking for instructions right before you said this. But also some images aren't rendering the same as the PR. I do see one that was done wrong but the product_management_admin shows the original images, not the changed images I see in github desktop.

https://deploy-preview-446--zencartdocs.netlify.app/user/template/page_format/
https://deploy-preview-446--zencartdocs.netlify.app/user/products/attributes_info/
https://deploy-preview-446--zencartdocs.netlify.app/user/products/category_management/admin
https://deploy-preview-446--zencartdocs.netlify.app/user/products/product_management_admin/
https://deploy-preview-446--zencartdocs.netlify.app/user/products/attributes_info/

**Comment by scottcwilson** [comment]
Not sure.  Let's merge and see how it looks in a few minutes when it's live.

**Comment by scottcwilson** [comment]
Some images still need work: 

page_phone.png it's 500 wide, let's go with 400.
attributes.png is 800 wide please go to 400
move_category_sidebar.png is perfect, but delete_category_sidebar.png is too small -please make delete_category_sidebar.png 350 wide like move.

**Comment by scottcwilson** [comment]
You will need to update your fork and then create a new PR.

**Comment by wiztechinc** [comment]
yup, the one I spotted  - glad to reduce the other two.

**Pull request merged**
