### PR TITLE
Image resizing 2

### PR DESCRIPTION
**Pull request by wiztechinc**
three resized images

### CODE REVIEW

**Comment by wiztechinc** [comment]
https://5f43f8da62a1180008fd6433--zencartdocs.netlify.app/user/products/category_management_admin/
https://5f43f8da62a1180008fd6433--zencartdocs.netlify.app/user/products/attributes_info/
https://5f43f8da62a1180008fd6433--zencartdocs.netlify.app/user/template/page_format/

**Comment by scottcwilson** [comment]
Look at the message saying "This branch has conflicts that must be resolved."  That tells me you didn't update your fork of the project.  Save your images off, get back in sync, delete this PR and try again.

**Comment by wiztechinc** [comment]
Blast, I did update it. But maybe too soon? I didn't think so.

**Comment by scottcwilson** [comment]
The branch was created when you had something else checked out - the prior branch? 

https://github.com/wiztechinc/documentation/tree/image-resizing-2

Always go back to master THEN create your new branch.

**Comment by wiztechinc** [comment]
new branch each time? Is that what I missed? I'm sure that's logical...but I didn't think that direction.

**Comment by wiztechinc** [comment]
I did a revert. Was that correct? I can't tell.

**Comment by scottcwilson** [comment]
Yes you must create a new branch every time. 
This one won't work either.

**Pull request closed without merging**
