### PR TITLE
Consolidate pointers to forum, clean up misc pages

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
Given this more-questions footer has value on all `user` pages, perhaps we should render it via the `user` template?

Does copying [content.html](https://github.com/google/docsy/blob/master/layouts/_default/content.html) to `/layouts/user/content.html` and then inserting the call to the shortcode after `.Content` accomplish this result in a suitable way?

**Comment by scottcwilson** [comment]
I love that idea - please merge what you have and I'll try it. I'll repurpose the shortcode so people can see how to use it.

**Comment by drbyte** [comment]
Okay. Careful though, normally we only want people editing `/content` pages, not the core template files.

**Comment by scottcwilson** [comment]
This template idea worked beautifully.  Good suggestion.

**Pull request merged**
