### PR TITLE
clarify admin menu sorting

### PR DESCRIPTION
**Pull request by torvista**

### CODE REVIEW

**Comment by scottcwilson** [comment]
Also I want to retain the versioning information so people with older installs don't get confused.

**Comment by torvista** [comment]
You mean you want me to add this instead  of replace it?

**Comment by scottcwilson** [comment]
Correct

**Comment by torvista** [comment]
ok, done.

**Comment by scottcwilson** [comment]
You'll have to create a new PR; this one was closed and I can't reopen it since it was force-pushed.

**Pull request closed without merging**
