### PR TITLE
Update Site specific Admin Overide Documentation

### PR DESCRIPTION
**Pull request by brittainmark**
Update documentation to include new packing slip image override
Add downloads manager page should show the file date
Update order display options for packing slip change

### CODE REVIEW

**Comment by scottcwilson** [comment]
Flipping to draft - will merge after 1.5.8a releases. Don't want to update before then.

**Comment by brittainmark** [comment]
Fine by me. just wanted to make sure you had a chance to read and approve.

**Comment by scottcwilson** [comment]
You might want to add "(since 1.5.8a)" or some similar language to let people know this is a new change that is not available in the first 1.5.8 release.  This kind of thing is very difficult to do in a clear way.

**Comment by scottcwilson** [comment]
Please take the file `content/user/admin/site_specific_overrides.md` out of this PR.   I'm going to remove those specific code examples, since they're already in the `dist-site_specific_admin_overrides.php` file.

**Comment by brittainmark** [comment]
Removed as requested.

**Comment by brittainmark** [comment]
Don't think this is needed any more.

**Comment by scottcwilson** [comment]
Just a note for documentation: this content *is* now in the help.  Thanks for authoring this.

**Pull request closed without merging**
