### PR TITLE
Point the Github icon to the doc repo

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
Hmmm. Is this really ideal?

**Comment by scottcwilson** [comment]
I'm not strong on this but it seems odd to not have the doc readme point to the doc repo.

**Comment by drbyte** [comment]
readme? 

This icon is the one in the very bottom right corner, isn't it?

**Comment by scottcwilson** [comment]
Sorry, yes, "home page".

**Comment by scottcwilson** [comment]
I will close since this is controversial.  We have good cross linking coverage on the home page.

**Pull request closed without merging**
