### PR TITLE
change separator

### PR DESCRIPTION
**Pull request by scottcwilson**
As requested in #1124

### CODE REVIEW

**Comment by drbyte** [comment]
Better. Thanks.

Any thoughts on how to insert at least a space between titles, where all of them are concatenated?
Screen Shot 2024-01-10 at 8 33 59 PM

**Comment by scottcwilson** [comment]
We might want to de-index that page - it's a bit hairy since it pulls in other pages.  This doesn't happen elsewhere, does it?

**Comment by scottcwilson** [comment]
Weird.  This file already has the directive to prevent indexing.

**Comment by drbyte** [comment]
I've told Algolia to exclude that path, and removed it from the index. Ideally that means it won't re-add it in tonight's crawl.

**Pull request merged**
