### PR TITLE
Fix white blank space beneath footer on large screen sizes

### LINKED ISSUE #915: White band below footer
Although more noticeable on large window sizes a white band has appeared below the footer. I think this was introduced with the addition of the footer's ADA/WCAG link. I'll try to take a look once I've finished with the foldable sidebar menu.

### PR DESCRIPTION
**Pull request by simon1066**
Fixes #915

Remove `min-height` constraint from footer.

### CODE REVIEW

**Comment by simon1066** [comment]
There was I thinking I had checked the heck out of this. This PR seems to fix the white space on all pages **except** the homepage. I think that this code change will still be apply but I'll add to this branch if I get a fix for the homepage.

**Comment by simon1066** [comment]
It was a long day yesterday. The blank space below the footer on the main page was introduced as part of a commit (https://github.com/zencart/documentation/commit/4f09e625c356b2bd0237ab216c322f593c1dc9c0) to make the home page fit on a desktop screen,  so nothing else to do here and this PR is still required for all other pages.

**Comment by scottcwilson** [comment]
@dbltoe Would you please address?

**Comment by dbltoe** [comment]
The checkers must not check CSS syntax.  This change is not quite correct in syntax and does not fix the problem.

The change I made did not interject a problem, it just showed the incorrect background more than before due to removing space between items on the page.  'Twas my fault for not taking full screen (F11) into effect at the time.

All that needs to be added to my original fix is:
'footer {min-height:100%;}'

Or this change 
'/* Footer - remove min-height constraint */

footer {
    min-height: auto;

    @include media-breakpoint-down(md) {
        min-height: auto;
    }
}'
Should become
'footer {min-height:100%;}'

But I cannot change the file from simon's fork.

Fixed with #920

**Comment by scottcwilson** [comment]
Seems like a bit more tweaking is required - the black part of the bottom of the screen should be limited in size.

**Comment by scottcwilson** [comment]
I went ahead and made this change in my own branch so we wouldn't have to deal with the merge conflicts.  Thanks guys!

**Pull request closed without merging**
