### PR TITLE
Update 158_order_language_files.md

### PR DESCRIPTION
**Pull request by proseLA**

### CODE REVIEW

**Comment by scottcwilson** [comment]
This is not really right.  The file  `lang.order_status.php` was introduced in 1.5.8; there has never been a file called `order_status.php` in the `languages` folder.  That's why this file is being ignored.

**Comment by scottcwilson** [comment]
Also if you do it for a file that *did* exist in prior releases, it causes logs.  

Example: Using PHP 8.1+, ZC 2.0.0: 
- copy from 1.5.7 the file `includes/languages/english/products_all.php` to `includes/languages/english/responsive_classic`.
- Load the all products page
- Observe duplicate definitions logs in logs folder.

That's why the guidance is to only use old style language files for plugins. 

https://docs.zen-cart.com/dev/code/158_language_files/

**Comment by proseLA** [comment]
> This is not really right. The file `lang.order_status.php` was introduced in 1.5.8; there has never been a file called `order_status.php` in the `languages` folder. That's why this file is being ignored.

my intention with this example was NEVER about the specific file.

> Also if you do it for a file that _did_ exist in prior releases, it causes logs.
> 
> Example: Using PHP 8.1+, ZC 2.0.0:
> 
> * copy from 1.5.7 the file `includes/languages/english/products_all.php` to `includes/languages/english/responsive_classic`.
> * Load the all products page
> * Observe duplicate definitions logs in logs folder.
> 
> That's why the guidance is to only use old style language files for plugins, and not to override them.
> 
> https://docs.zen-cart.com/dev/code/158_language_files/

this example is not about guidance.  it is about how the code works.

furthermore, i am talking about templates, not plugins.

i was not involved in the development of the language loader and the necessary changes.  i observed from afar.

from my perspective the whole idea of having a template is to insulate users/store owners from having to update template files when there is a core update.  barring, of course, breaking changes in the underlying technology, ie php upgrades.

this language loader goes against that perspective, ie, that override file will no longer work.

store owners running v157 and upgrading could have language override files that no longer override the language.  and when doing an update, that's a problem that perhaps someone would refer to the docs; like i did.  

the example provided is an example of how the language loader works; but it does NOT say anything about the situation that i experienced.

my example is an example that is more nuanced, and i think more applicable that potentially someone would see.  it does not provide guidance.

you are correct that duplicate logs are created.  IMO, this is a fault of the code and inherent in the design.  my code design would NOT load either of the 2 style default language files if there is 1 of either type in an override directory.  but again, as i said, i was not involved in it, and even if i was, there is no guarantee that my design idea would have been accepted.  i can see potential arguments against it.

**Comment by scottcwilson** [comment]
> IMO, this is a fault of the code and inherent in the design. 

There are other ways of doing this, yes, but this is what was done.  The easiest way forward is for you to follow the guidance posted above.   Really, the best practice is just to convert to the new format, then there's never an issue.

**Pull request closed without merging**
