### PR TITLE
Deployment options

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
I believe elsewhere we've defined terms like "document root", which is the "home directory filepath" that Apache points the domain to, to find the site's files. eg: `public_html`.

One configuration not mentioned here is editing the hosting account to specify the docroot. This lets you put your store into any directory on the filesystem and point the entire domain to that directory.

One reason why knowing the docroot is important, is for the concept of relocating non-public-needed store files outside the docroot, making them secure from bad actors.

Not urgent to incorporate, but something to mull over for a future update, integrating it into other pages that discuss related concepts.

**Comment by scottcwilson** [comment]
I like this idea - we have sort of introduced it in https://docs.zen-cart.com/user/security/relocate_download_folder/.
Let me create an issue and noodle on it.

**Comment by scottcwilson** [comment]
> One configuration not mentioned here is editing the hosting account to specify the docroot. This lets you put your store into > any directory on the filesystem and point the entire domain to that directory.

Can you write a few sentences about the use case?  I know it's possible to do - but other than multi-tenant, I can't visualize *why* someone would do this. 

(I do agree on your later point that knowing your document root is important so you can move download files outside of that, but I haven't seen people move around document root.)

**Comment by drbyte** [comment]
I've made a note to go and write something about that, perhaps on the weekend.

A good use-case: I'm upgrading my store. I can stage the new site's files in its own directory, and then when it comes time to go-live, I can just change the docroot and immediately the new files are active. No editing of config files, no renaming of directories, etc.
Admittedly it's a little more advanced of a concept, but for those who "get it" (and have access to it), it's a convenient way to version-control your site. (And you can rollback to old code just by changing the docroot to the previous directory. (notwithstanding database, which most of the time isn't a reason for a rollback anyway)). This "renaming the docroot" (esp via symlinks) is the way a lot of enterprise "no down time" deployments happen: everything is staged in its own dir, and when it comes time to go live, the dir is changed, usually via a symlink edit. Visitors never know the difference because it's instant.

I've seen (only a few) Zen Cart shops do this. They like it because of the version-control-esque benefit it offers.
Gotta mull it over before tackling how to document it simply. I might just be very brief for the sake of "mentioning it, without going into detail", where advanced devops folks will get it but others who don't will just ignore it and move on.

**Comment by scottcwilson** [comment]
Definitely an advanced topic.  If you can write a few sentences that would be great!

**Pull request merged**
