### PR TITLE
last of images & html

### PR DESCRIPTION
**Pull request by wiztechinc**
user/admin_pages/tools/store_manager.md
 user/admin_pages/catalog/product_types.md
 user/admin_pages/reports/graphical_sales_report.md
 user/first_steps/secure_access.md
 user/first_steps/yes_you_need_ssl.md

and images

### CODE REVIEW

**Comment by wiztechinc** [comment]
see one problem already in html.

**Comment by wiztechinc** [comment]
https://deploy-preview-452--zencartdocs.netlify.app/user/admin_pages/catalog/product_types/ 
have 2, one hasn't been removed. Revert the commit?

**Comment by scottcwilson** [comment]
You never have to revert for a PR.  Just save off your work, delete the PR, and go back to master and do it again.  In this case I just fixed it for you.

**Comment by wiztechinc** [comment]
Thanks. I’ve lost so much work in the dang app. Next time I’ll give it a try.

**Comment by scottcwilson** [comment]
OK there are Issues marked "Help Wanted" - pick one you'd like to work on and just update it, and I'll assign it to you.

**Pull request merged**
