### PR TITLE
Test environment changes from @dbltoe

### PR DESCRIPTION
**Pull request by scottcwilson**
Please review @dbltoe.   Changes have been made for cross linking and terminology standardization.

### CODE REVIEW

**Comment by dbltoe** [comment]
Like the inclusion of standard terminology.  Admittedly, I'm not familiar enough with it and didn't take the time to research it.

I'm still not happy with 38.  You cannot properly test all server idiosyncracies on a local server.  Saying every serve is the same is just as false as saying all Zen Cart installations are the same.

We are talking test here and the only way to completely test is in the very environment that will be used.

Was this an upgrade versus a test, doing most of the work on a local computer might make sense.  Again, the statement was IF you have high-speed internet (even 5M), the advantage may very well be in favor of on-server work.

Admittedly, I'm sitting on 500/250 but, I still prefer to work on the server vs locally.

Also, on line 124, I would add something like "If you go to your **_test** folder, do a **Select All**, and **Compress** these files into **test_basic.zip**, you will have a clean backup to revert to in further testing. If you find that the mod you've tested is going to be part of your main store, do the zip process again, calling it **test_MOD-NAME.zip**.  You can build as many fall-back zips as you need."

**Comment by drbyte** [comment]
Observations:

The document in question is about a "local test environment", which by convention means "my local PC, not a remote server".

While 80% of concepts are similar in both cases, there's a lot of periphery that's unique to the actual environment, and none of it actually has anything to do with Zen Cart, but rather with "hosting".

**Comment by scottcwilson** [comment]
@drbyte What if we split this content off into a separate page?  Final testing before Golive?

John, can you perhaps write up the kinds of key differences you're seeing between live and test that make live testing so critical?  In my experience this has never been a real problem, and I'm having trouble understanding why you'd want to work this way for anything but the last 5% of testing.

**Comment by drbyte** [comment]
There's a difficult balance to maintain in the topic of upgrading. If the docs look too long and complicated peoples brains shut down and decide to skip the whole thing.

If it's too detailed for one particular environment (hosting platform) then people not on that platform are led down the wrong path, or at least have to somehow figure out how many of the next paragraphs apply or don't apply to them. 

Also, when it's very specific about one hosting platform then any time that hosting platform makes a tiny change our docs become out of date. 
Writing more generically avoids that maintenance issue.
For example, if you're writing a bunch of steps related to cPanel's file manager and zipping a file, why not just cross-link to their docs for that and just say "If you're using cPanel, you can zip the file as shown in their docs at http // ......."

**Comment by scottcwilson** [comment]
I guess my concern is that the proposed method is extremely error prone.  It's almost never the case that a configuration issue on the server causes problems, whereas I hear ALL THE TIME from people who swear they uploaded all the files ... who didn't ... you know ... upload all the files.  Failure to upload is cited as the number one root cause of problems in https://docs.zen-cart.com/user/troubleshooting/blank_page/

**Comment by drbyte** [comment]
Okay, after re-reading, I think this is what I'd like to see:

Given that a common question people have is "how do I create a secondary testing store", it makes sense that this document could fill that gap, and since these additions are almost all not about "testing" anything, but rather "Setting up a secondary testing store on your server", let's create a separate document by that name.  

Perhaps put the "non-cPanel-alternatives" footer up at the top in a blockquote (markdown syntax would be `>` to start it off).

Then maybe the single-line statement about "testing" could crosslink to another doc about testing things, if that makes sense.

**Comment by scottcwilson** [comment]
I really like that idea.  @dbltoe Please resubmit at your convenience.  I will close this PR.

**Pull request closed without merging**
