### PR TITLE
index-listing changes

### PR DESCRIPTION
**Pull request by wiztechinc**
more changes for clarity and cross-linking

### CODE REVIEW

**Comment by scottcwilson** [comment]
OK this is good but please keep going.  Looking at the default data: 

http://localhost:8888/demo_157/index.php?main_page=index&cPath=2

shows categories.  We're calling this a Categories page.  What can I do here with admin settings?

If you drill down further, 

http://localhost:8888/demo_157/index.php?main_page=index&cPath=2_20 

shows products.  We're calling this a product listing page.  What can I do here with admin settings?

**Comment by wiztechinc** [comment]
I had a slight headache which has just increased. I'm not sure what you are saying.  Expand further on the section about categories/subcategories? You said admin settings - are you referring to just these settings or over all in the cart? Yes, I can see more discussion somewhere else on these points.

**Comment by scottcwilson** [comment]
The focus would be on admin settings, like the ones you have already described.

**Comment by wiztechinc** [comment]
Besides the fact I've been under the weather since last Thursday, I really have reached a point that requires me to do something else - I have to have a better grasp of how the documentaion is organized and what has been written up til now. I am a big picture person, used to planning and writing materials, including books. Chewing at this bit by bit is actually quite difficult for me. 

So unless you have a great overview such as a mind map (not site map tho that might help some), I have to stop writing and start reading and documenting it all. I have no choice.

**Pull request merged**
