### PR TITLE
example htaccess redirects

### PR DESCRIPTION
**Pull request by torvista**
Despite there being a world of info out there on .htaccess, getting redirects to work as expected proved incredibly frustrating and time-consuming, due to lack of experience/not seeing anything about rewrites being processed first until late in the day, and urls being separate to the query parameters. So this is an attempt to document that and hopefully prevent others' frustration.
No doubt more experienced users can add more.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Looks good.  Please change the symbols in the last two blocks so they're enclosed in backticks - this makes it more obvious.

Old:

^ - start of the string to match  

New:

`^` - start of the string to match

**Comment by torvista** [comment]
I think they all look better in backticks.

**Comment by dbltoe** [comment]
FYI, I've had no problems in the past using the tools from https://tools.websiteadvantage.com.au/HtAccess-301-Redirect-Generator#heading-ToolResult.
Sometimes a free tool is helpful as well.

**Comment by torvista** [comment]
looks good, stick in the docs too!

**Comment by scottcwilson** [comment]
Great!  Thanks for this contribution.

**Pull request merged**
