### PR TITLE
Adding images to sidebox list

### PR DESCRIPTION
**Pull request by wiztechinc**
Expanded and added images to sidebox list with some text rewrites.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Thanks.  One file is missing - the information sidebox.

Remember that when you create a PR you get a preview (the last link in the list of checks) so you can see how your work will look when it goes live.   This is a useful way of tracking down Markdown errors if you're not running a Hugo instance locally. 

If you have more time it would be helpful to get this file formatted.  Use ## (or ###) for titles.  Remember you have to preserve the front matter at the top of the file - you can't change the dashes to stars or it won't work.

**Comment by wiztechinc** [comment]
First time with md files!  

Hmm, well information is in the file I had. So the titles that I had added are not necessary? Found that in an instruction somewhere.

Didn't realize I could preview! Major cool. 

So title instead of bold? No problem.  Will fix. I did deliberately not bold all. Make all titles?

**Comment by scottcwilson** [comment]
Yes please - make each grouping a title. 

To add titles to the individual sideboxes you could use a smaller title (### vs ##) or make them bullets - whichever you like.

**Comment by scottcwilson** [comment]
> Hmm, well information is in the file I had.

Sorry for the lack of clarity - I meant to say that the file `/images/sidebox_information.png` is missing - did you call it `/images/information_sidebox.png` by chance?

**Comment by wiztechinc** [comment]
Nope, just didn't copy it over to the right folder.   Now that I can see it online, I see I really need to look closer at formatting this one. Will work on it. Would you rather I commit the one image first and do the other later?

**Comment by scottcwilson** [comment]
also as a suggestion, it would be good to place the images side by side when there are multiple under the same header (Banners, Manufacturers, Reviews, etc.)    Just remember if you are using HTML to use a blank line between that and the markdown.  

Do things in whatever order you see fit.

**Comment by wiztechinc** [comment]
I did have different titles for each banner box - I feel folks really need those cues - so very hard to tell them apart so wasn't intending there to be several images without that text. Also titled each box if there was more than one in a list item.  If you changed that, I assume you disagree?  It does make it harder to format the list for sure. I do feel that some of them need more info - I added links to existing documentation but I can create more pages if it's a reasonable way to do this. Food for thought.

Think I got the edits as I want - with the extra titles per box. Let me know what you think at your leisure before I do another commit.

**Comment by scottcwilson** [comment]
I had to remove the titles because your stuff wasn't working and I just wanted to fix it as quickly as possible.   You forgot to space between markdown and HTML, you had extra content where the filename was, the front matter was broken, etc. 

Titles would be good.  The best way to do this is to have Hugo running locally as described here:

https://github.com/zencart/documentation

if you can't do this, then submit a PR but mark it draft so I know it's not ready to merge, and iterate as you test.  It's best to use "git commit --amend" (and "git push --force") so you are smashing the commits into a single commit as you go.

**Comment by scottcwilson** [comment]
This might be an interesting exercise for you.  Create a new PR with your original submission - but rename the file (so as not to break the new sidebox_list.md) and clearly mark the file and PR as test work only.  Then look at the preview from the build and see all the problems.  Try tweaking it and fixing the problems.  As long as it's clearly marked it will be fine.

**Comment by scottcwilson** [comment]
When you break the front matter (as you did) the file won't even show up in the list of sidebox pages.  You'll have to navigate to it by entering the URL in your browser.

**Comment by wiztechinc** [comment]
I forgot...nothing. First time with markdown. Thanks for your patience and suggestions! I’ll get there hopefully quickly and try to lessen the work on you in the meantime.

**Comment by scottcwilson** [comment]
Another thing which could be done would be to explain the purpose of the boxes.  For example, **More Information** contains the 3 extra define pages, whereas **Information** contains Privacy, Contact Us, etc. I can never seem to remember that - I have to look at the code each time.  So it certainly wouldn't be readily apparent to a new person.

**Comment by wiztechinc** [comment]
Exactly!

**Comment by wiztechinc** [comment]
So when I started on the page, I wanted to add those details right there as that is the way I would do an html page. Best way in that situation would be a list of anchor links up top that link further down for each box info which really would require a back to top button or some such navigation aid. I would prefer something like that instead of having to access another page for each box. But with mobile space contraints and coding restraints with markdown, I have no idea what the possibilities are. I know that html anchor links are of course possible here. Do you think it's appropriate/advisable?

**Comment by scottcwilson** [comment]
I'd say just fill it out each screenshot with a description - it's not such a huge page that you really need in-page navigation. 

I'm not saying a page per box - if you look at how the Information box is laid you, you have the screenshot and then the description right next to it.  Just copy that.

**Comment by wiztechinc** [comment]
ah, I'm used to SEOing the crap out of stuff so would never have thought of putting text in the image.  Got Hugo installed so working with figuring out how to use it.

**Comment by wiztechinc** [comment]
at last - after spending a lot of time and some money to get Hugo working on my computer, it was a wash. I hired someone and he was buffaloed why it wouldn't work but I have a much better handle on markdown now and I think I can make this work without it. 

If there are any problems - it may just be different text in the images or the page. I expect discussion on what I wrote. Somewhere I read how to do the images so that folks can see the images before the commit / in dev but I can't find that instruction again and you didn't mention that with the first commit. I thought it said to do /images/ Is it possible to fully preview images in github here?

**Comment by scottcwilson** [comment]
Just submit your PR and we'll look at it together.  Remember to start the path to images with a slash: `/images`.   Just make a note that the PR is not ready to merge in case someone comes along.

**Comment by wiztechinc** [comment]
Okay, will do.

**Pull request merged**
