### PR TITLE
Adding foldable functionality to sidebar menu sections (with search box tweaks)

### LINKED ISSUE #847: Possible changes to Section Menu
I do find the left menu sidebar to be a bit difficult to navigate. The sidebar defaults with all sections expanded, showing all pages - that's a lot to scroll through. It's only after clicking on a section heading that everything but that section collapses, that's a bit more manageable but can still be a lot of pages to scroll through to get to the next section (First Steps for example).

I note that the Docsy submodule Zen Cart Docs uses hasn't been updated in 3/4 years, since then there has been a foldable section menu introduced, as exampled on this page:  https://deploy-preview-518--docsydocs.netlify.app/docs/adding-content/navigation/#section-menu

### PR DESCRIPTION
**Pull request by simon1066**
Fixes #847 & #914

The initial plan to include the search box in the sidebar has been dropped as Algolia DocSearch will not function in a sidebar (https://www.docsy.dev/docs/adding-content/navigation/#adding-algolia-docsearch), while the search box has been removed the hamburger navigation remains for small/mobile window sizes as a useful aid. The search box remains in the header for small screens.

`config.toml` Added foldable sidebar menu to site parameters.

`assets/scss/_variables_project.scss` Adjusted sizes of left column and main content area to accommodate foldable sidebar sections.

`assets/scss/_sidebar-tree.scss` Removed previous customisation by @drbyte as no longer needed following recent Docsy theme update.

`assets/scss/styles_project.scss` General styling to accommodate all screen sizes.

`layouts/partials/sidebar-tree.html` This Docsy theme override file has been removed as previous edits are no longer needed.

### CODE REVIEW

**Comment by scottcwilson** [comment]
@simon1066 Where do we stand on this PR?  I thought there was an issue with it but I don't see anything in the Conversation.

**Comment by simon1066** [comment]
As far as I was aware it worked and was ready to go, that was last September though and I haven't looked at it since - I assumed it was low priority and put on the back-burner. Not sure if my PR has been affected by changes to Hugo or the Docsy template that _might_ have been applied in the meantime, I'm a bit busy at the moment so am not sure I can delve deep to fully refresh my memory.

**Comment by simon1066** [comment]
Had a chance to re-test this PR, it's still applicable and is good to go.

**Comment by drbyte** [comment]
Looks good to me. Thanks for fixing this!

**Comment by scottcwilson** [comment]
@drbyte, if you can support any issues that arise, merge now, otherwise I will merge when back in office in mid Aug.  Thanks so much for doing this @simon1066 - this will improve the experience of browsing the help, especially on mobile.

**Comment by simon1066** [comment]
I too should be available to look at any issues that might arise.

**Comment by drbyte** [comment]
> I too should be available to look at any issues that might arise..
> 

Thanks Simon!

**Pull request merged**
