### PR TITLE
White area at the bottom of Full Screen Main Page

### PR DESCRIPTION
**Pull request by dbltoe**
Fixes problem mentioned in #917

### CODE REVIEW

**Comment by scottcwilson** [comment]
Much obliged!

**Comment by scottcwilson** [comment]
Still seems a tad wonky - see if you can improve it further.  (The black part at the bottom of the page shouldn't go on for a full screen.) Thanks.

**Comment by dbltoe** [comment]
THANX.  It does make the site footers a little long but that's just room to add supporters/ads.  😃 

I'm looking now

**Comment by scottcwilson** [comment]
Opened new issue #921 to track.

**Pull request merged**
