### PR TITLE
Add AWS details

### PR DESCRIPTION
**Pull request by scottcwilson**
@drbyte please review

### CODE REVIEW

**Comment by drbyte** [comment]
What are your thoughts on putting this in `user/products/download_delivery_methods` instead?

There's pros and cons. Your thoughts?

**Comment by scottcwilson** [comment]
Considered it - we could *mention* it in both places and link from the shorter one to the longer one.

**Comment by drbyte** [comment]
I've updated the filename to be a link to the file on github.

The other page probably deserves more details than what's said here. Can cross-link later if that section is added.

**Comment by scottcwilson** [comment]
TY. Will create a new issue for you to document this at your convenience.

**Pull request merged**
