### PR TITLE
Update yes_you_need_ssl.md

### PR DESCRIPTION
**Pull request by dbltoe**
Just tightening the meaning and adding freebies at some hosts

### CODE REVIEW

**Comment by drbyte** [comment]
> have an SSL

`SSL` is not a noun. It's an acronym.

I'd prefer instead of `an SSL` we use just `SSL` or possibly maybe `SSL Certificate`.

**Comment by scottcwilson** [comment]
I like "have an SSL certificate."

**Comment by drbyte** [comment]
Thinking about it more I realize that the reason I usually use `SSL` instead of `SSL Certificate` is that I'm usually referring more to the overall underlying technology than to just a certificate alone. 

I suppose to the less-techy storeowner it might make more sense to talk about using `HTTPS` instead of `SSL`. (But somewhere explain that they are synonyms.)

**Comment by drbyte** [comment]
I'll merge this and we can deal with the wording choice separately.

**Pull request merged**
