### PR TITLE
Tools for translation of English strings in database

### PR DESCRIPTION
**Pull request by piloujp**
Detailed information on how to find and convert English languages strings in database to make translation of admin menus easier.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Thank you for contributing your work, @piloujp !

**Comment by piloujp** [comment]
There is still a small problem I can't find a solution: In regular expressions replacement parts, lines start with 4 spaces to fit language files format. As it was not rendering properly in .md format, I replaced them at last minute by `\s{4}` which actually does not work in a replacement pattern. I was thinking of 4 non-breakable spaces instead but as this is inside 'code tag', it will just display `&nbsp;&nbsp;&nbsp;&nbsp;`. I am new to markdown format, perhaps somebody has a solution?

**Comment by piloujp** [comment]
I found the solution. On my Windows system, I type Alt+0160 in text editor and Mardown file keep it as is.

**Comment by scottcwilson** [comment]
If you use triple backtick the spacing your want is preserved: 

```
    'CFGTITLE_$3' => '$2',\r    'CFGDESC_$3' => '$4',
```

Does that help?

**Comment by drbyte** [comment]
Triple-backtick to denote a section of rows to treat as "code".
Or single-backtick to wrap some characters within a line, denotes them as code.

Spaces at the end of a line aren't visible.

**Comment by piloujp** [comment]
Triple backtick actually keep spaces, but the whole line appears as code. For inline code marking with a single backtick, multiple spaces are reduced to one for any reason...
In this case, the only solution I found was non-breakable spaces directly entered from keyboard. You just have to know how to write it on your system.

**Pull request merged**
