### PR TITLE
Update sidebox_list images/text

### PR DESCRIPTION
**Pull request by wiztechinc**
reworked images, edited text, layout, markdown

### CODE REVIEW

**Comment by scottcwilson** [comment]
You have to put a "/" before Images.
Also the headers shouldn't have a dash before them.  I fixed the first few and the merge conflict so you can see.

**Comment by scottcwilson** [comment]
Click the last "Details" link that says "Deploy preview" and see how it looks.

**Comment by wiztechinc** [comment]
Sorry, I had but then I got entangled. Will correct after lunch.

**Comment by scottcwilson** [comment]
Keep me posted if you get stuck.  You're well on the way!  
Also I think the older images were better - putting the instructions in the sidebox image makes it too small to see.

**Comment by scottcwilson** [comment]
I really think the way I did the More Information sidebox is the way to go here.  Did you not like that? 

https://docs.zen-cart.com/user/sideboxes/sidebox_list/#information

**Comment by wiztechinc** [comment]
> I really think the way I did the More Information sidebox is the way to go here. Did you not like that?
> 
> https://docs.zen-cart.com/user/sideboxes/sidebox_list/#information

I didn't notice. This is all so very backwards. Really I feel like I'm going backwards in time. Okay, inline css it is. 

So do you always use the html for the images instead of markdown?

**Comment by scottcwilson** [comment]
I would suggest abandoning this PR and pulling out the markdown file, then resubmitting a new one (since you don't really want these images).  Use the existing images, and remember to add in the missing one (I think it's Information). 

I generally use markdown for image formatting - however: markdown (the one this system uses) does not have a way to create a table.  So if you want to use a table, the way I did for the Information box, you have to use HTML.

I also will use HTML to display an image if I have to reduce the size.

**Comment by scottcwilson** [comment]
You will want to start a brand new branch off master to do this.

**Comment by scottcwilson** [comment]
One good approach would be to create a new branch and just fix the other information sidebox the way the existing one works - just add in the formatting and the image (which was missing from the first checkin).  Then we can merge that and you'll be confident in your change.

**Comment by wiztechinc** [comment]
well, now I'm getting frustrated for several reasons so I'll pick this up again tomorrow. There's way too much going on here and without an effective way to view these files as I work, I'm really struggling. Some of those images you did need a tad of editing. The OCD graphic designer in me can't let that go. I think one of the problems is that I want to do too much in a commit.

**Comment by scottcwilson** [comment]
No worries - it all takes time and Rome wasn't built in a day.  I'm totally ok with editing the existing images if you can improve them.  (I just don't want a big chunk of the image taken up by text.)   And it's totally ok to do multiple commits within a PR or multiple PRs - for a large change that's often the best strategy.  

Standing by waiting for your next update.

**Comment by wiztechinc** [comment]
Went for a walk to clear (kinda) my head.
Question (not criticism). Why can't we use one additional css file instead of writing inline css? I only do simple - that's why I dislike bootstrap and the big css packages. If it's well-documented, it should be easy for folks to follow (and would get rid of my biggest headache right now). I certainly can write inline css but it takes more time to write it out.  I don't want to do anything that hinders someone else from helping but you know I'm all in for the documentation and this is the best way for me to contribute (to prevent going totally insane in today's insane world).

**Comment by scottcwilson** [comment]
It's a lot more work - the Hugo package already includes a lot of CSS.  And it won't be easy for you to do if you don't have Hugo to test locally.  But if you want to see how it's done, look at 

https://github.com/zencart/documentation/blob/master/CONTRIBUTING.md

and search down for "CSS."

**Comment by wiztechinc** [comment]
simple css like .left for float left .right for float right .clearBoth for obvious reasons. Just some basic stuff that I wouldn't expect to be an issue but of course anything is possible for conflicts. And yes need Hugo to fully view this kind of change on multiple pages. Back to the original source of frustration.  I did the images just now.

**Comment by wiztechinc** [comment]
I got Hugo working! This will definitely make it all easier.

**Comment by scottcwilson** [comment]
Closing this one out.

**Comment by wiztechinc** [comment]
Sorry, but the sideboxes list does not display the same as it does online. The sass isn't working which was the problem we never overcame  before. (i'm missing the border around the images as the most obvious part of this).  This time I never got the error message saying it didn't compile.  The html doesn't show either in the browser and then I have the opposite problem in Typora which previews automatically.  I can see the html but not the images that are markdown. If I try to preview in github, I don't see the extra html.

**Comment by scottcwilson** [comment]
If you want to create a new PR with your work, I can look at it.

**Comment by wiztechinc** [comment]
definitely tomorrow. I really need to do something else! Anything else.

**Pull request closed without merging**
