### PR TITLE
Image caching

### PR DESCRIPTION
**Pull request by wiztechinc**
new image_caching.md, 3 new images and changes to change_header_logo.md. I added some text about hard refreshes as that is the way I deal with the problem but remove if you think inappropriate.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Thank you!   Two small points: 

- Be sure any new page is self-sufficient.  The original content of the new page wouldn't have made sense unless you came to it directly from the logo page.
- If you're fixing an issue, put a comment like Fixes #408 in the first comment for a PR.  (You can edit this if you forget to do it when you submit the PR).  This means the issue will automatically get closed when your PR is merged.

You can see your handiwork now live! 

https://docs.zen-cart.com/user/new_user_topics/image_caching/

Fantastic, this is exactly what I wanted.

**Comment by drbyte** [comment]
FYI I made a couple small tweaks:

- changed "if you upload an image of the same name" from "same name" to "same filename", for clarity.
- added sub-point to the image-caching page that the same symptom can occur with CSS and JS files.

**Comment by scottcwilson** [comment]
VERY good point - I have had that pain many times with CSS.  Thanks for doing this.

**Comment by scottcwilson** [comment]
Renamed and retitled the file to just "caching" - covers images plus CSS/JS.

**Pull request merged**
