### PR TITLE
Docs referenced in Zen Cart code

### PR DESCRIPTION
**Pull request by scottcwilson**
I have the corresponding Zen Cart code changes ready to go as soon as this is merged and I can double check the new URLs.

### CODE REVIEW

**Comment by drbyte** [comment]
Can we skip the authnet stuff?

**Comment by scottcwilson** [comment]
We could ... but it's still referenced in 
	includes/languages/english/modules/payment/authorizenet.php
	includes/languages/english/modules/payment/authorizenet_aim.php

**Comment by drbyte** [comment]
So are all the links to those docs from hundreds of forum posts. The pages aren't going away, so let's not change those language files needlessly.

**Comment by scottcwilson** [comment]
Wouldn't it be better to have redirects (or even links) in the old pages so you would only have to maintain these pages in one place?

**Comment by drbyte** [comment]
> Wouldn't it be better to have redirects (or even links) in the old pages so you would only have to maintain these pages in one place?

Ya, at some point we'll figure out some massive list of redirects.

But as you know those authnet modules are deprecated. There won't be updates to those modules, so there won't be updates to the doc page either. Why ...

scratch that. 
Fine. Whatever.

**Comment by drbyte** [comment]
Don't get me wrong. I'm grateful for all the work you're putting into this.

I just have so much stuff going on I can't put brainpower into the bigger rewrites plan, and would like to minimize the additional load that could cause. 

But, as you say, we can always delete these docs later.

**Comment by scottcwilson** [comment]
I didn't realize Authorize was deprecated!   

> Ya, at some point we'll figure out some massive list of redirects.

I wonder if you could get away with less ... even just updating content.php to say "This page is deprecated; please see the new page on the new site."  
It's a pain, but they only have to navigate and bookmark the new site one time.

**Pull request merged**
